### ISSUE TITLE
discuss the best PATCH semantic to update

### ISSUE THREAD

**Issue by toumorokoshi** [aep-dev/aeps#109]
We should revisit if we want to support the AIP's field mask protocol. Maybe look at JSON patch semantics.

**Comment by toumorokoshi** [comment]
some disadvantages of field masks:

- doesn't give a good way to specify that you want to include the object, but you don't know about all of it's subfields.
- except for proto3 optional, doesn't give a good way to specify null.

**Comment by mkistler** [comment]
Why not use JSON merge patch?

**Comment by rofrankel** [comment]
Other shortcomings of `FieldMask`:

* Explicitly conflicting guidance in [the proto](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/field_mask.proto) vs. the Google AIPs:
  * The AIP says "the service must treat an omitted field mask as an implied field mask equivalent to all fields that are populated (have a non-empty value)."; the protos says "If a field mask is not present on update, the operation applies to all fields (as if a field mask of all fields has been specified)."
* Useful behavior specified in the AIP but not mentioned by the proto docs:
  * About whether you can specify subfields of repeated fields (the AIP supports the `*` wildcard; the proto docs do not).
  * The AIP says field mask of `"*"` represents full replace (`PUT`); the proto docs don't mention this.
  * The AIP says "Field masks may permit the specification of specific fields in a map, if and only if the map's keys are either strings or integers, using the . character for traversal."; the proto doesn't mention this.
* Limited when it comes to repeated fields (only supports append; no way to remove values, full-replace the repeated field, or index into a repeated field.

Strengths of FieldMask:

* Has a compact JSON representation that works well as a query parameter (it's just comma-separated field paths)
* Is also used for read masks; using the same structure for both read and update masks may or may not be a good thing (but I don't think it'd make sense to use JSON Patch for read masks).

I don't know jsonpatch.com well enough to know how many of these problems it solves, or how many new ones it introduces, but at a glance it supports:

* Removing and replacing repeated field values.
* Indexing into repeated fields.
* Implicitly, indexing into map fields (which in JSON are not distinct from message fields)

Some shortcomings of JSON Patch:

* If you need to refer to a key with `~` or `/` in its name, you must escape the characters with `~0` and `~1` respectively. For example, to get `"baz"` from `{ "foo/bar~": "baz" }` you’d use the pointer `/foo~1bar~0`.
* It is substantially more powerful than FieldMask; we might not want to force API owners to have to support e.g. the copy operation, which could be a expensive (or even infeasible) for some systems to implement.  So we might have to define a subset of the spec for APIs to support.

**Comment by mkistler** [comment]
I think that both Microsoft and IBM have standardized on JSON Merge patch for "update".

https://datatracker.ietf.org/doc/html/rfc7386

### Strengths of JSON Merge Patch

- Easy for users to understand and implement.
- Naturally idempotent
- Well-defined semantics
- Robust to versioning

### Shortcomings of JSON Merge Patch

- Cumbersome to modify array values

**Comment by dv-stewarts** [comment]
Is this issue and https://github.com/aep-dev/aep.dev/issues/15 still being worked on? It all seems to have gone quiet. https://aep.dev/134 is marked as approved but there is no guidance for OAS interfaces.

I can guess by reading AIP-134, AIP-127, and AIP-161, as well as the source code for FieldMask that the correct PATCH request would be something like what I have put below, but it's definitely not clear. I assume I shouldn't be relying on AIPs to interpret AEPs and the water is further muddied by the various discussions on JSON Patch/JSON List Patch/JSON Merge Patch.
```
PATCH /v1/resource/{id}?updateMask=a.b,c,d
{
  "a": {
    "b": "hello"
   },
  "c": "world",
  "d": "foo",
  "e": "this field would be ignored because it's not in the updateMask."
}
```

**Comment by toumorokoshi** [comment]
Hi there! It is in the queue, sorry we haven't updated publicly. I'll document the offline discussion that followed this. 

For OAS / HTTP + JSON APIs, we've tentatively agreed upon JSON merge (RFC 7396): https://datatracker.ietf.org/doc/html/rfc7396. It handles all the cases we enumerated around object and field existence. 

For proto APIs - they should use a layer that translates JSON-merge-patch into a field mask + update object. We've discussed that field masks don't have the full functionality required to articulate what is required for json merge patch (e.g. you can't set an object to non-null, but not set any of it's properties), but we're still deliberating on what to do there.

The reason we can't recommend JSON merge-patch for protos is because the semantic equivalent isn't possible without all values being nullable (proto's wire protocol automatically interprets missing values as the default value).

I'll try to at least get a PR out so the tentative guidance is available.

Details:

- There's an [exploration in this document](https://docs.google.com/document/d/1wajQv4CGr2mtmPfVy77zIyi022IUW0xg6JmRkj3gA0s/edit#heading=h.gwrs6kwx4hln) that has a discussion around various formats.

Separately:

> https://aep.dev/134 is marked as approved but there is no guidance for OAS interfaces.

This is a good point approved means "we agree with all the guidance stated" not necessarily "the AEP is complete". But we are trying to work toward adding OAS representations of all schemas.
